### ISSUE TITLE
I can't get the configuration to work.

### ISSUE THREAD

**Issue by amarakon** [dylanaraps/pfetch#149]
I set environmental variables such as PF_ASCII="openbsd" in a .profile folder and it didn't do anything

**Comment by yuri-norwood** [comment]
What operating system are you using? Have you tried running `PF_ASCII="OpenBSD" pfetch`?

Try running `pfetch` normally, and then with `PF_ASCII="OpenBSD" pfetch`, you should see that the ASCII changes. 
![image](https://user-images.githubusercontent.com/76186754/132268847-ca8348b6-ea96-4232-a3de-2a69988823e3.png)

To make the change permanent, you also need to `export` the variable to your environment, not just set it. Try running `pfetch` normally again, then call `export PF_ASCII="OpenBSD"`, now you can run `pfetch` without setting the ASCII variable again. This setting will last as long as your shell session lasts.

![image](https://user-images.githubusercontent.com/76186754/132269135-f9369bce-c447-420a-8204-0e2b9da8a904.png)

As is noted in the [README](https://github.com/dylanaraps/pfetch#configuration), pfetch is controlled via environmental variables, you can set these in your `~/.profile` if you have it set up, but the environment variables can come from anywhere.

Also, it sounds like you have a *directory* named `.profile` instead of a *file*, also make sure that the file is in your `$HOME` directory and is executable.

Note: see also #143

**Comment by amarakon** [comment]
Running PF_ASCII="openbsd" pfetch works like it should, but putting PF_ASCII="openbsd" in my .profile doesn't change pfetch. It's also executable and in my home directory.
This is what my .profile looks like:
#!/usr/bin/env sh

PF_ASCII="openbsd"

**Comment by amarakon** [comment]
My operating system is Artix Linux, but I'm doing PF_ASCII="openbsd" just for testing purposes so that I can do more configurations later on.

**Comment by amarakon** [comment]
Also I'm using the fish shell and the alacritty terminal of that is useful info.

**Comment by dylanaraps** [comment]
You need to export the environment variables. If using fish, refer to fish's documentation.

**Comment by TheThunderGuyS** [comment]
Fish does not source anything from .profile, as it is POSIX incompatible (instead put `set -gx PF_ASCII "openbsd"` in `~/.config/fish/config.fish`). Please refer to your shell's manual before asking for help.
